---
- name: Print facts
  hosts: all
  # gather_facts: False
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution
    - name: Print memory
      debug:
        var: ansible_memory_mb
    - name: Print processor mame
      debug:
        var: ansible_processor[2]
