---
- name: Dbserver setup
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla
  tasks:
    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: present

    - name: Install python3-pymysql
      apt:
        name: python3-pymysql
        state: present

    - name: Start service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create database user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
